### ISSUE TITLE
Change Link format in AddOn

### ISSUE THREAD

**Issue by overeha** [code4romania/emergency-news-addon#16]
Do we have the option of formatting the links. 
Can the add-on display taxt and have links on the text. 
The links area should look like this
”1. Centralizator de știri oficiale
2. Departamentul pentru Situații de Urgență
3. Ministerul Sănătății”

all three texts should be clickable links.

**Comment by andreicristianpetcu** [comment]
So basically all links need to have a caption? I need to change the json file format.

**Comment by andreicristianpetcu** [comment]
On local dev. Will be in next version.
![image](https://user-images.githubusercontent.com/922368/77197591-22fd2e80-6aee-11ea-91aa-8b8f6e99fce5.png)

same version
![image](https://user-images.githubusercontent.com/922368/77197778-6ce61480-6aee-11ea-99a7-cec640e45965.png)

The styles are totally different due to pages interfering with our CSS. There is a separate issue for that.
