### ISSUE TITLE
Contextual highlight

### ISSUE THREAD

**Issue by catileptic** [code4romania/emergency-news-addon#35]
We should only highlight any terms which do not contain the virus name if the virus name already exists in the DOM. 

This way we avoid highlighting terms in any text that is not related to Covid-19.

**Comment by iFlex** [comment]
Allright, I got the gist of what's needed here (had an in depth look at the code) - so the terms need to be as varied as possible but related to coronavius in order to highlight as many relevant sections of the page as possible without false positives. However, the current structure of the terms.json makes that pretty hard to do since each term variation has a copy of the title, links and explanations. 

This will become unmanageable as more variation on terms are added. Say you have 50 terms for the covid sickness - all of them pointing to the same links - and one of the links changes. That change needs to be done in 50 places in stead of 1. 

I'll put together a change that will allow the json to be changed easily without massively duplicating records and add as many terms as I can think of with covid-19 and other variations included - if that's ok with you. Took a look at the issues list for this project and it seems nobody's doing this already.

**Comment by catileptic** [comment]
We're working on the terms so that they don't all use the same few links. We launched with a very small set of words and of links, since the pressure was large. 

If you have a better idea for the JSON structure, please feel free to create a PR and let's discuss.

**Comment by andreicristianpetcu** [comment]
@iFlex sounds good. Please go on and propose a new JSON format. I wanted to do this some time ago but I rushed with more issues.Here is what I wanted to be able to do, maybe not in your initial proposal but on the long term:
 - top level version, just like manifest.json has
 - no objects flying around. we need to always have key value pairs. I want to be able to change the structure of the json in the future. Quite hard right now for example since the top level item is an array of terms.
 - we need links as top level elements, like you said.
 - no HTML in JSON. We currently have < p > entries. I want them out. They actually would allow remote code execution and I don't feel ok with that.
 - terms.json will say where it is. we are not deleting it. It's being fetched by old versions of the extension. The new format will be a new file, which I hope we will be able to stick to for more.
 - the terms will be a list of objects that will contain the term identifier. Now we need to do [crazy hacks](https://github.com/code4romania/emergency-news-addon/blob/52b03826a63d13ba2d953c1b4a1c55d628fb5fa9/src/background.js#L15-L40) after loading the term in order to be sure we [do matches on longer patterns first](https://github.com/code4romania/emergency-news-addon/blob/52b03826a63d13ba2d953c1b4a1c55d628fb5fa9/src/emergency_news.js#L70-L93) like "simptome coronavirus" will be matched before "coronavirus" since it's more explicit

Any issues you see with the current format, please feel free to dump here :smile:

**Comment by andreicristianpetcu** [comment]
We don't need to have everything re-done in one shot, just agree on the format and once we do, we can merge it in the source, even if it's not used. Since the old format is set in stone due to it being loaded remotely we have the freedom to change the new file without actually using it.

Are you able to run the extension locally?

**Comment by iFlex** [comment]
@andreicristianpetcu  yep - ran it locally and discovered the crazy hacks :D 
My observations so far are the same as yours - having top level links makes the json more manageable in time as it grows and changes. 
I need to jump on a call, but will be back with the proposal.

**Comment by iFlex** [comment]
@andreicristianpetcu Here's my proposal for the JSON

{
	"version":1,
	"name":"COVID-19 Official News Sources Per Topic",
	"topics":{
		"topic1":{
			"title": "Title of the topic2",
        	"explanation": "Short explanation topic1, no HTML here. Just pure text",
        	"links": ["info link 1","info link 2"]
		},
		"topic2":{
			"title": "Title of the topic2",
        	"explanation": "Short explanation topic2, no HTML here. Just pure text",
        	"links": ["info link 1","info link 2"]
		}
	},
	"mappings":{
		"keywords to match":["topic1"],
		"keyword to match2":["topic2"],
		"keyword to match3":["topic3"],
	}
}

- Top level version and name of the data object
- Topics: an established dictionary of topics and the associated explanation, title and links
- Mappings: a key:value dictionary that matches a variation of keywords related to one or more topics to the correct topics (the values in this array need to match the keys in topics)
- In order to implement the most specific first match policy, the keys of mappings can be sorted by length in the extension code or "mappings" can become an array where the order set from the json file.
- For now we can have only one topic for each mapping key, but I propose keeping the value an array because in the future we might come up with ways to show links from multiple topics - handled in the client code no need to change the json to adjust for that. 

Thoughts?

**Comment by iFlex** [comment]
Here's an example of how it could look like for the topics of coronavirus and autoizolare:
{
    "version":1,
    "name":"COVID-19 Official News Sources Per Topic",
    "topics":{
        "#coronavirus":{
            "title": "Coronavirus",
            "explanation": "Informează-te din surse oficiale. Nu toate știrile care circulă pe internet sunt și corecte. Când citești informații despre subiectul pandemiei verifică informația cu sursele oficiale. <p>Acestea sunt disponibile aici:</p>",
            "links": [
                "https://www.stirioficiale.ro",
                "http://www.dsu.mai.gov.ro/category/http10-1-100-213dsuindex-phpcategoryuncategorized/",
                "http://www.ms.ro/coronavirus-covid-19/"
            ]
        },
        "#autoizolare":{
            "title": "Autoizolare",
            "explanation": "În mod obligatoriu, românii care se întorc în țară din zone de risc vor trebui să intre în autoizolare la domiciliu, ceea ce presupune ca întreaga familie să facă același lucru.<p>NU intrați în contact direct cu persoanele aflate în autoizolare la domiciliu, indiferent dacă prezintă sau nu simptome specifice coronavirus. Dacă vă aflați în autoizolare la domiciliu respectați cu strictețe recomandările autorităților, NU părăsiți sub nicio formă domiciliul pe perioada celor 14 zile, NU primiți vizitatori și NU intrați în contact apropiat cu eventualele persoane care vă furnizează alimente sau produse.</p><p><b>În cazul în care încălcați regimul autoizolării la domiciliu riscați amendă de până la 20.000 de lei, precum și dosar penal în cazul în care contribuiți la răspândirea virusului.</b><p>Mai multe informații găsiți aici:</p>",
            "links": [
                "http://www.ms.ro/recomandari-privind-conduita-sociala-responsabila-in-prevenirea-raspandirii-coronavirus-covid-19/"
            ]
        }
    },
    "mappings":{
        "covid-19":["#coronavirus"], 
        "Coronavirusul":["#coronavirus"],
        "Coronavirusului":["#coronavirus"],
        "coronaviruses":["#coronavirus"],
        "COVID-19":["#coronavirus"],
        "covid-19":["#coronavirus"],
        "coronavirus 2019":["#coronavirus"],
        "coronavirus 2020":["#coronavirus"],
        "coronaviruși":["#coronavirus"],
        "virus wuhan 2019":["#coronavirus"],
        "virus wuhan 2020":["#coronavirus"],
        "virus wuhan 2019":["#coronavirus"],
        "autoizolat covid-19":["#autoizolare"],
        "autoizolării covid-19":["#autoizolare"],
        "autoizolați covid-19":["#autoizolare"],
        "izolare covid-19":["#autoizolare"],
        "izolare la domiciliu covid-19":["#autoizolare"],
        "izolare acasă covid-19":["#autoizolare"],
        "autoizolare la domiciliu covid-19":["#autoizolare"],
        "autoizolare acasă covid-19":["#autoizolare"],
        "autoizolat covid-19":["#autoizolare"],
        "autoizolării coronavirus":["#autoizolare"],
        "autoizolați coronavirus":["#autoizolare"],
        "izolare coronavirus":["#autoizolare"],
        "izolare la domiciliu coronavirus":["#autoizolare"],
        "izolare acasă coronavirus":["#autoizolare"],
        "autoizolare la domiciliu coronavirus":["#autoizolare"],
        "autoizolare acasă coronavirus":["#autoizolare"]
    }
}

**Comment by andreicristianpetcu** [comment]
@iFlex I think it's a good start. I made a few updates:
 - topics as identifiable objects in an array. I think it's better like this since arrays are ordered, unlike objects.
 - paragraphs as an array of strings since if we only have text without fromatting it will look like a big wall of text. Paragraphs can make things more readable.
 - we should be able to change the link title or URL and re-use it in the rest of the file
 - added enabling terms for the extension to pick up the context
 - mappings as identifiable objects

```json
{
    "version": 1,
    "name": "COVID-19 Official News Sources Per Topic",
    "topics": [{
            "id": "topic1",
            "title": "Title of the topic2",
            "paragraphs": ["Short explanation topic1, no HTML here. Just pure text"],
            "linkIds": ["stiri-oficiale"]
        },
        {
            "id": "topic2",
            "title": "Title of the topic2",
            "paragraphs": ["Short explanation topic2, no HTML here. Just pure text"],
            "linkIds": ["stiri-oficiale"]
        }
    ],
    "terms": [{
        "id": "coronavirus",
        "aliases": [
            "Covid-19"
        ]
    }],
    "mappings": [{
        "termId": "coronavirus",
        "topicId": "topic1"
    }],
    "links": [{
        "id": "stiri-oficiale",
        "href": "https://",
        "title": "COVID-19 ȘTIRI OFICIALE"
    }],
    "pageEnablingTermIds": [
        "coronavirus"
    ]
}

What do you say?

**Comment by iFlex** [comment]
@andreicristianpetcu - I complete decoupling between objects. What do we need aliases for in this format? Since the mappings achieve that functionality

**Comment by andreicristianpetcu** [comment]
@iFlex it's easy to add a synonim without grasping the full structure of the json

**Comment by iFlex** [comment]
@andreicristianpetcu allright, so we'll keep those but not use them in code then and apply the correct structure later?

**Comment by andreicristianpetcu** [comment]
Thank you for your interest. This is a pretty urgent issue and we decided to postpone accepting PRs until the project becomes a bit more mature.
Your input on this issue was valuable.

**Comment by andreicristianpetcu** [comment]
The format mentioned above is very hard to use. I implemented this with this related format. Ids are very error prone.
https://github.com/code4romania/emergency-news-addon/blob/2fd71a7a1ab6a99d5a639cad42ff74e1a28b744f/src/config.json
